INSERT INTO country (name, iso) VALUES 
('Bulgaria', 'BG'),
('USA', 'US'),
('Canada', 'CA'),
('Mexico', 'MX'),
('Brazil', 'BR'),
('Germany', 'DE'),
('France', 'FR'),
('Spain', 'ES'),
('Italy', 'IT'),
('UK', 'GB'),
('Australia', 'AU'),
('Japan', 'JP'),
('China', 'CN'),
('India', 'IN'),
('South Korea', 'KR'),
('Russia', 'RU'),
('South Africa', 'ZA'),
('Argentina', 'AR'),
('Egypt', 'EG'),
('Nigeria', 'NG'),
('Chile', 'CL');

INSERT INTO [user] (username, [password], email, birthdate, picture_url, phone, is_admin, karma, country_id) VALUES
('john_doe', 'password123', 'john.doe@example.com', '1990-05-01', 'http://example.com/pic1.jpg', '1234567890', 0, 10, 1),
('jane_smith', 'password123', 'jane.smith@example.com', '2004-03-12', 'http://example.com/pic2.jpg', '2345678901', 0, 15, 2),
('alex_brown', 'password123', 'alex.brown@example.com', '2009-08-20', 'http://example.com/pic3.jpg', '3456789012', 1, 50, 2),
('lucas_lee', 'password123', 'lucas.lee@example.com', '1982-01-15', 'http://example.com/pic4.jpg', '4567890123', 0, 30, 4),
('emily_white', 'password123', 'emily.white@example.com', '2008-11-30', 'http://example.com/pic5.jpg', '5678901234', 0, 5, 1),
('oliver_martin', 'password123', 'oliver.martin@example.com', '1993-06-25', 'http://example.com/pic6.jpg', '6789012345', 0, 12, 2),
('mia_taylor', 'password123', 'mia.taylor@example.com', '1991-02-09', 'http://example.com/pic7.jpg', '7890123456', 1, 75, 7),
('daniel_wilson', 'password123', 'daniel.wilson@example.com', '1987-07-07', 'http://example.com/pic8.jpg', '8901234567', 0, 20, 4),
('isabella_jones', 'password123', 'isabella.jones@example.com', '1992-09-18', 'http://example.com/pic9.jpg', '9012345678', 0, 18, 2),
('sebastian_garcia', 'password123', 'sebastian.garcia@example.com', '1994-12-02', 'http://example.com/pic10.jpg', '0123456789', 0, 22, 1),
('ava_davis', 'password123', 'ava.davis@example.com', '1970-11-28', 'http://example.com/pic11.jpg', '1234567890', 0, 14, 11),
('jackson_smith', 'password123', 'jackson.smith@example.com', '1993-07-22', 'http://example.com/pic12.jpg', '2345678901', 0, 35, 2),
('lily_moore', 'password123', 'lily.moore@example.com', '1989-10-17', 'http://example.com/pic13.jpg', '3456789012', 0, 25, 4),
('henry_clark', 'password123', 'henry.clark@example.com', '1985-04-14', 'http://example.com/pic14.jpg', '4567890123', 1, 60, 14),
('lucy_scott', 'password123', 'lucy.scott@example.com', '1998-01-08', 'http://example.com/pic15.jpg', '5678901234', 0, 8, 1),
('matthew_robinson', 'password123', 'matthew.robinson@example.com', '1992-03-29', 'http://example.com/pic16.jpg', '6789012345', 0, 18, 16),
('olivia_baker', 'password123', 'olivia.baker@example.com', '2010-12-19', 'http://example.com/pic17.jpg', '7890123456', 0, 7, 17),
('zachary_harris', 'password123', 'zachary.harris@example.com', '1996-06-04', 'http://example.com/pic18.jpg', '8901234567', 0, 9, 2),
('chloe_miller', 'password123', 'chloe.miller@example.com', '1991-12-01', 'http://example.com/pic19.jpg', '9012345678', 0, 5, 19),
('ethan_wilson', 'password123', 'ethan.wilson@example.com', '1986-05-21', 'http://example.com/pic20.jpg', '0123456789', 0, 11, 1);

INSERT INTO subreddit (title, [description], rules, created_at, user_id) VALUES 
('Technology', 'All about the latest in technology', 'No spam, no pirated content', GETDATE(), 1),
('Music', 'Discuss all things music-related', 'Be respectful', GETDATE(), 2),
('Gaming', 'Talk about the latest games and trends', 'No hate speech', GETDATE(), 3),
('Movies', 'Movie lovers unite!', 'No spoilers without warning', GETDATE(), 4),
('Books', 'For avid readers', 'Respect others'' opinions', GETDATE(), 2),
('Food', 'Share your recipes and food tips', 'No offensive content', GETDATE(), 6),
('Art', 'Post and discuss art', 'Be kind to artists', GETDATE(), 7),
('Sports', 'Everything about sports', 'Keep it friendly', GETDATE(), 8),
('Science', 'Discuss science and discoveries', 'No misinformation', GETDATE(), 8),
('Travel', 'Share your travel experiences', 'Respectful language', GETDATE(), 10),
('Finance', 'Financial advice and discussions', 'No personal attacks', GETDATE(), 1),
('Fitness', 'For all things fitness', 'Be positive', GETDATE(), 12),
('Pets', 'For animal lovers', 'Respect all animals', GETDATE(), 8),
('Education', 'Learn and discuss various topics', 'Stay on topic', GETDATE(), 2),
('News', 'Breaking news from around the world', 'Keep it civil', GETDATE(), 15),
('History', 'Explore historical events', 'Respect others’ views', GETDATE(), 1),
('Cars', 'Talk about cars and vehicles', 'No spam or self-promotion', GETDATE(), 3),
('Photography', 'Showcase your photography skills', 'Credit your sources', GETDATE(), 3),
('Crafts', 'Discuss and share crafts', 'No hate speech', GETDATE(), 3),
('Nature', 'Discuss all things nature-related', 'Respect the environment', GETDATE(), 20);

INSERT INTO moderator (user_id, subreddit_id) VALUES 
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5),
(6, 6),
(7, 7),
(8, 8),
(9, 9),
(10, 10),
(11, 11),
(12, 12),
(13, 13),
(14, 14),
(15, 15),
(16, 16),
(17, 17),
(18, 18),
(19, 19),
(20, 20);

INSERT INTO follow (created_at, follower_id, followed_id) VALUES 
(GETDATE(), 1, 11),
(GETDATE(), 2, 12),
(GETDATE(), 3, 13),
(GETDATE(), 4, 14),
(GETDATE(), 5, 15),
(GETDATE(), 6, 16),
(GETDATE(), 7, 17),
(GETDATE(), 8, 18),
(GETDATE(), 9, 19),
(GETDATE(), 10, 20),
(GETDATE(), 11, 1),
(GETDATE(), 12, 2),
(GETDATE(), 13, 3),
(GETDATE(), 14, 4),
(GETDATE(), 15, 5),
(GETDATE(), 16, 6),
(GETDATE(), 17, 7),
(GETDATE(), 18, 8),
(GETDATE(), 19, 9),
(GETDATE(), 20, 10);

INSERT INTO message (created_at, text, sender_id, receiver_id) VALUES
(GETDATE(), 'Hello, how are you?', 5, 12),
(GETDATE(), 'Did you get the file I sent?', 8, 17),
(GETDATE(), 'Can we meet tomorrow?', 3, 9),
(GETDATE(), 'Let me know when you''re free.', 11, 15),
(GETDATE(), 'Thanks for the update!', 14, 7),
(GETDATE(), 'Let''s finalize the project details.', 6, 18),
(GETDATE(), 'Happy birthday!', 10, 20),
(GETDATE(), 'Can you call me later?', 2, 16),
(GETDATE(), 'Don''t forget about the meeting at 2 PM.', 19, 4),
(GETDATE(), 'The presentation was great!', 13, 1),
(GETDATE(), 'What are your thoughts on the proposal?', 7, 3),
(GETDATE(), 'I will send over the documents shortly.', 16, 8),
(GETDATE(), 'Are you available for a quick chat?', 9, 14),
(GETDATE(), 'Let''s catch up soon.', 4, 13),
(GETDATE(), 'I really appreciate your help.', 1, 11),
(GETDATE(), 'Can you review this draft?', 17, 6),
(GETDATE(), 'I''ll be late to the meeting.', 12, 10),
(GETDATE(), 'Great job on the report!', 18, 2),
(GETDATE(), 'Let''s have a quick sync-up tomorrow.', 15, 19),
(GETDATE(), 'Thanks for your patience.', 20, 5);

INSERT INTO membership (created_at, user_id, subreddit_id) VALUES
(GETDATE(), 1, 10),
(GETDATE(), 2, 10),
(GETDATE(), 3, 10),
(GETDATE(), 4, 10),
(GETDATE(), 5, 7),
(GETDATE(), 6, 7),
(GETDATE(), 7, 7),
(GETDATE(), 8, 19),
(GETDATE(), 9, 19),
(GETDATE(), 10, 2),
(GETDATE(), 11, 2),
(GETDATE(), 12, 2),
(GETDATE(), 13, 2),
(GETDATE(), 14, 2),
(GETDATE(), 15, 2),
(GETDATE(), 16, 13),
(GETDATE(), 17, 13),
(GETDATE(), 18, 9),
(GETDATE(), 19, 9),
(GETDATE(), 20, 8);

INSERT INTO post (title, text, created_at, user_id, subreddit_id) VALUES 
('New Tech in 2024', 'Discuss the latest gadgets coming out this year', GETDATE(), 1, 1),
('Top 10 Games of 2024', 'Here are the best games of 2024 so far', GETDATE(), 2, 3),
('Best Horror Movies Ever', 'Let''s talk about the scariest movies ever made', GETDATE(), 3, 4),
('Best Books for 2024', 'Recommended books to read this year', GETDATE(), 4, 5),
('Delicious Vegan Recipes', 'Here are some amazing vegan recipes to try', GETDATE(), 5, 6),
('New Art Trends', 'What is the future of art?', GETDATE(), 6, 7),
('NBA Finals Predictions', 'Who will win the NBA Finals this year?', GETDATE(), 7, 8),
('NASA Mars Mission', 'What is NASA planning for the next Mars mission?', GETDATE(), 8, 9),
('Travel Destinations in 2024', 'The best places to visit this year', GETDATE(), 9, 10),
('Stock Market Analysis', 'Let''s analyze the stock market trends this month', GETDATE(), 10, 11),
('Home Workout Routines', 'Here are some easy workout routines to try at home', GETDATE(), 11, 12),
('Best Pet Foods for Dogs', 'What are the healthiest foods for dogs?', GETDATE(), 12, 13),
('How to Study for Finals', 'Share your tips and tricks for acing exams', GETDATE(), 13, 14),
('Breaking News: Global Event', 'A major global event just happened, discuss here', GETDATE(), 14, 15),
('Ancient Civilizations', 'Let''s explore the ancient civilizations of the world', GETDATE(), 15, 16),
('New Car Models', 'Check out the latest car models in 2024', GETDATE(), 16, 17),
('Best Photography Gear', 'What is the best camera gear for beginners?', GETDATE(), 17, 18),
('DIY Craft Ideas', 'Fun craft projects to do at home', GETDATE(), 18, 19),
('Sustainable Living', 'How can we make our lifestyle more sustainable?', GETDATE(), 19, 20),
('Wildlife Conservation Efforts', 'Let''s talk about wildlife conservation', GETDATE(), 20, 20);

INSERT INTO topic (title, description) VALUES
('Technology', 'Discuss the latest trends and innovations in technology.'),
('Politics', 'Share and debate your views on political events and policies.'),
('Fitness', 'Talk about workouts, health tips, and staying active.'),
('Travel', 'Share travel experiences and destination recommendations.'),
('Cooking', 'Discuss recipes, cooking tips, and food-related stories.'),
('Gaming', 'Talk about video games, gaming culture, and reviews.'),
('Science', 'Explore the latest discoveries and advancements in science.'),
('Books', 'Share book recommendations and discuss your favorite reads.'),
('Movies', 'Discuss films, reviews, and the latest in cinema.'),
('Music', 'Share your favorite songs, artists, and music trends.'),
('Education', 'Discuss learning resources, methods, and experiences.'),
('Finance', 'Talk about saving, investing, and personal finance tips.'),
('Sports', 'Discuss the latest games, teams, and sports news.'),
('Health', 'Share advice and experiences about physical and mental health.'),
('Fashion', 'Talk about trends, style tips, and personal preferences.'),
('Art', 'Discuss visual arts, share creations, and get inspired.'),
('History', 'Explore historical events, facts, and interesting stories.'),
('Pets', 'Share advice, tips, and stories about your furry friends.'),
('Environment', 'Discuss sustainability, climate change, and green living.'),
('Photography', 'Share tips, techniques, and your best shots.');

INSERT INTO comment (text, created_at, user_id, post_id) VALUES 
('I totally agree! Technology is advancing so fast!', GETDATE(), 1, 1),
('This is so true, 2024 has been great for gaming!', GETDATE(), 2, 2),
('I love horror movies, definitely going to check out some of these!', GETDATE(), 3, 3),
('I need to read more, thanks for the recommendations!', GETDATE(), 4, 4),
('These recipes look amazing! Going to try some soon!', GETDATE(), 5, 5),
('The art world is changing so much. Can''t wait to see where it goes!', GETDATE(), 6, 6),
('I think the Lakers will win this year!', GETDATE(), 7, 7),
('Mars missions are so exciting, can''t wait for the launch!', GETDATE(), 8, 8),
('I want to visit Japan next year, thanks for the tips!', GETDATE(), 9, 9),
('Great analysis on the market, I''m keeping an eye on these trends!', GETDATE(), 10, 10),
('Home workouts are the best, no excuse not to get in shape!', GETDATE(), 11, 11),
('I always struggle to find the best dog food, this is helpful!', GETDATE(), 12, 12),
('Good luck on your exams everyone!', GETDATE(), 13, 13),
('The event really shook the world, glad we can discuss it here!', GETDATE(), 14, 14),
('Ancient history is fascinating! Looking forward to the discussion.', GETDATE(), 15, 15),
('I''m loving the new Tesla models!', GETDATE(), 16, 16),
('Definitely need a new camera, these suggestions are great!', GETDATE(), 17, 17),
('I just finished a craft project using these ideas, it turned out awesome!', GETDATE(), 18, 18),
('I love the idea of reducing waste. Going to look for more eco-friendly products!', GETDATE(), 19, 19),
('Wildlife conservation is something we need to talk more about!', GETDATE(), 20, 20);

INSERT INTO post_vote (vote_type, created_at, user_id, post_id) VALUES
(1 , GETDATE(), 1, 10),
(1, GETDATE(), 2, 10),
(1, GETDATE(), 3, 10),
(1, GETDATE(), 4, 10),
(1, GETDATE(), 5, 7),
(1, GETDATE(), 6, 7),
(0, GETDATE(), 7, 7),
(1, GETDATE(), 8, 19),
(0, GETDATE(), 9, 19),
(1, GETDATE(), 10, 2),
(1, GETDATE(), 11, 2),
(1, GETDATE(), 12, 2),
(0, GETDATE(), 13, 2),
(1, GETDATE(), 14, 2),
(0, GETDATE(), 15, 2),
(0, GETDATE(), 16, 13),
(1, GETDATE(), 17, 13),
(1, GETDATE(), 18, 9),
(1, GETDATE(), 19, 9),
(0, GETDATE(), 20, 8);

INSERT INTO comment_vote (vote_type, created_at, user_id, comment_id) VALUES
(1 , GETDATE(), 1, 13),
(1, GETDATE(), 2, 13),
(1, GETDATE(), 3, 13),
(1, GETDATE(), 4, 13),
(1, GETDATE(), 5, 8),
(1, GETDATE(), 6, 8),
(0, GETDATE(), 7, 6),
(1, GETDATE(), 8, 17),
(0, GETDATE(), 9, 17),
(1, GETDATE(), 10, 5),
(1, GETDATE(), 11, 5),
(1, GETDATE(), 12, 5),
(0, GETDATE(), 13, 3),
(1, GETDATE(), 14, 3),
(0, GETDATE(), 15, 3),
(0, GETDATE(), 16, 2),
(1, GETDATE(), 17, 2),
(1, GETDATE(), 18, 2),
(1, GETDATE(), 19, 14),
(0, GETDATE(), 20, 14);

INSERT INTO award_type (name) VALUES
('Gold'),
('Silver'),
('Platinum'),
('Rookie'),
('Supporter'),
('Dank'),
('Noodle'),
('Helpful'),
('Wholesome'),
('Silver Spoon'),
('Showerthought'),
('Gilded'),
('Caring'),
('Friendly'),
('Insightful'),
('Bravo'),
('Visionary'),
('Epic'),
('Champion'),
('Creative');

INSERT INTO post_award (created_at, award_type_id, user_id, post_id) VALUES
(GETDATE(), 1, 1, 13),
(GETDATE(), 1, 2, 13),
(GETDATE(), 2, 3, 12),
(GETDATE(), 2, 4, 10),
(GETDATE(), 3, 5, 9),
(GETDATE(), 3, 6, 9),
(GETDATE(), 4, 7, 16),
(GETDATE(), 4, 8, 8),
(GETDATE(), 5, 9, 10),
(GETDATE(), 5, 10, 3),
(GETDATE(), 6, 11, 1),
(GETDATE(), 6, 12, 20),
(GETDATE(), 7, 13, 20),
(GETDATE(), 7, 14, 7),
(GETDATE(), 8, 15, 7),
(GETDATE(), 8, 16, 18),
(GETDATE(), 9, 17, 4),
(GETDATE(), 9, 18, 3),
(GETDATE(), 10, 19, 2),
(GETDATE(), 10, 20, 2);

INSERT INTO comment_award (created_at, award_type_id, user_id, comment_id) VALUES
(GETDATE(), 1, 1, 11),
(GETDATE(), 1, 2, 11),
(GETDATE(), 2, 3, 16),
(GETDATE(), 2, 4, 4),
(GETDATE(), 3, 5, 4),
(GETDATE(), 3, 6, 2),
(GETDATE(), 4, 7, 20),
(GETDATE(), 4, 8, 14),
(GETDATE(), 5, 9, 14),
(GETDATE(), 5, 10, 14),
(GETDATE(), 6, 11, 1),
(GETDATE(), 6, 12, 1),
(GETDATE(), 7, 13, 7),
(GETDATE(), 7, 14, 6),
(GETDATE(), 8, 15, 6),
(GETDATE(), 8, 16, 6),
(GETDATE(), 9, 17, 6),
(GETDATE(), 9, 18, 3),
(GETDATE(), 10, 19, 2),
(GETDATE(), 10, 20, 2);

INSERT INTO subreddit_topic (subreddit_id, topic_id) VALUES
(1, 11),
(2, 12),
(3, 13),
(4, 14),
(5, 15),
(6, 16),
(7, 17),
(8, 18),
(9, 19),
(10, 20),
(11, 1),
(12, 2),
(13, 3),
(14, 4),
(15, 5),
(16, 6),
(17, 7),
(18, 8),
(19, 9),
(20, 10);

INSERT INTO post_topic (post_id, topic_id) VALUES
(1, 11),
(2, 12),
(3, 13),
(4, 14),
(5, 15),
(6, 16),
(7, 17),
(8, 18),
(9, 19),
(10, 20),
(11, 1),
(12, 2),
(13, 3),
(14, 4),
(15, 5),
(16, 6),
(17, 7),
(18, 8),
(19, 9),
(20, 10);
